config/routes.rb
Rails.application.routes.draw do

  resources :comments
  ## ignore any periods not followed by `json` and the EOS
  # permit_periods_in = lambda do |*vars|
  #   match = /[^\/]+(?=\.json\z)|[^\/]+/
  #   contraints = vars.map{ |var| [var, match] }.to_h
  #   return {constraints: contraints}
  # end
  ## use in place of the 'constraints' option, e.g.:
  ## resources :users, **permit_periods_in.(:email)

  resources :users
  resources :posts do
    member do
      post 'share'
    end
  end

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates   :slug,  required: false
  validates_uniqueness_of :slug,  scope: :user
  validates   :title, presence: true
  validates_uniqueness_of :title, scope: :user
  validates   :body,  presence: true
  validates   :user,  presence:  true

  mount_uploader :featured_image, FeaturedImageUploader

  default_scope { order(created_at: :desc) }

  extend FriendlyId
  friendly_id :slug
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :restrict_with_error

  has_secure_password
  has_secure_token

  validates :name,  presence: true
  validates :email, presence: true,
                    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action ->{
    @title = 'Everything is headcanon.'
    @accent_colors = %w(kalamata-olive-juice-on-a-paper-plate
                        subtly-pretentious-khaki-shorts
                        drowning-in-a-pre-raphaelite-sea
                        a-gentle-wednesday-poo)
  }

  private

  def scrub_html(how_and_what = {})
    restrictive = %w(i b a p q u s br em rt strong mark
                  del ins address cite bdo bdi sub sup
                  small h4 h5 h6 span progress wbr dfn
                  meter time abbr var kbd)
    permissive =  restrictive + %w(blockquote pre code h1
                  h2 h3 img ul ol li dl dt dd hr figure
                  figcaption svg summary details menuitem
                  canvas video source audio track iframe
                  map area samp noscript)
    filter = Rails::Html::PermitScrubber.new
    how = how_and_what.keys.first
    filter.tags = case how
    when :permissively
      permissive
    when :restrictively
      restrictive
    else
      raise 'Invalid option. Pass :permissively or :restrictively as a key with an HTML string value.'
    end
    what = Loofah.fragment(how_and_what[how])
    what.scrub!(filter)
  end

  def error_up(class_instance)
    errors = class_instance.errors
                           .full_messages
                           .map! { |error| { error: error } }
    Hash(json: { errors: errors },
         status: 401)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :show, :share]

  def index
    @posts = Post.all
  end

  def show; end

  def edit; end

  def share
    if params[share][:email].blank?
      flash[:warning] = 'Yo dog, give me an email address so I know where to send this post.'
      render :share
    else
      UserMailer.share(@post, params[share][:email]).deliver
      flash[:success] = 'You did great!'
      redirect_to @post
    end
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(summary: scrub_html(restrictively: auto_summary),
                    title:   params[:post][:title],
                    body:    scrub_html(permissively: params[:post][:body]),
                    slug:    auto_slug,
                    user:    User.find(params[:post][:user_id]),
                    featured_image: params[:post][:featured_image],
                    remote_featured_image_url: params[:post][:remote_featured_image_url])
    post.save ? redirect_to("/posts/#{post.slug}") : render(error_up(post))
  end

  def update
    post = Post.find_by(slug: params[:post][:slug]) # TODO: Replace find_post
    if post.update(title: params[:post][:title],
                   body:  params[:post][:body],
                   slug:  params[:post][:slug])
      render(json: post)
    else
      render(error_up(post))
    end
  end

  private

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def sanitized_args
    params.require(:post).permit(:id,
                                 :slug,
                                 :title,
                                 :body,
                                 :summary,
                                 :user_id,
                                 :featured_image)
  end

  def auto_summary
    generated_summary = -> { params[:post][:body][0...255] }
    params[:post][:summary].blank? ? generated_summary.call : params[:post][:summary]
  end

  def auto_slug
    generated_slug = lambda do
      params[:post][:title].parameterize
                           .downcase[0...255]
    end
    params[:post][:slug].blank? ? generated_slug.call : params[:post][:slug]
  end

  # def adopt_image
  #   image = params[:post][:featured_image]
  #   prefix = 'http://res.cloudinary.com/dux9qimrr/image/fetch/'
  #   # String === image ? prefix + image : image
  #   if String === image
  #     image = FeaturedImageUploader.new.store!(prefix + image)
  #   else
  #     image
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:edit, :show, :update]

    def index
      @users = User.all
      render json: @users
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        UserMailer.signup(@user).deliver
        redirect_to @user
      else
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit
      end
    end

  private

  def user_params
    params.require(:user)
          .permit(:email,
                  :name,
                  :password,
                  :avatar,
                  :banner)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_core.html.erb
<section id="site-core" class="column">
    <div class="row center-block">
      <main id="content" class="col-lg-6 col-lg-offset-2">

        <%= yield %>

      </main>
      <aside id="sidebar" class="col-lg-2">

        <%= render partial: 'sidebar' %>

      </aside>
    </div>
    <%= render partial: 'popular' %>
</section>

app/views/application/_footer.html.erb
<footer id="site-footer">
    Copyright &copy; 2017
</footer>

app/views/application/_header.html.erb
<header id="site-header">
    <h1>
        <%= link_to root_path do
            @title
        end %>
    </h1>
</header>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to root_path, class: "navbar-brand" do %>
              <%= image_tag "logo-headcanon.svg", class: "img-responsive" %>
            <% end %>
            <%= link_to @title.upcase, root_path %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
          <% if !@post&.id.blank? %>
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to 'Edit This Post', edit_post_url(@post[:id]) %>
                </li>
            </ul>
          <% end %>
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to 'New Post', new_post_url %>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to 'Sign Up', new_user_url %>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="Search">
                    <i class="glyphicon glyphicon-search form-control-feedback"></i>

                </div>
            </form>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/application/_popular.html.erb
<footer id="popular" class="column center-block">
  <h1>MOST POPULAR</h1>
  <div class="row center-block">
    <% Post.order(views: :desc)[0...4].each_with_index do |post, i| %>
      <div class="popular col-lg-3 <%= @accent_colors[i] %>">
        <%= link_to post do %>
          <%= render html: sanitize(post.summary) %>
        <% end %>
      </div>
    <% end %>
  </div>
</footer>

app/views/application/_sidebar.html.erb
<div class="column">
    <div class="row center-block">
        <div id="sidebar-inner" class="col-lg-12">
            <img src="/assets/logo-headcanon-loop.svg" />
            <h3>John Hill MacDonald</h3>
            <h4>About me</h4>
            <p>
              Brother of George MacDonald. Existential poet. Works reproduced in his brother's novels. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>
          <%= @title %>
        </title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render partial: 'nav' %>
        <%= render partial: 'header' %>
        <%= render partial: 'core' %>
        <%= render partial: 'footer' %>
    </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="bg-danger col-lg-12">
    <ul class="list-unstyled">
      <% @post.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @post do |f| %>
  <%= f.association  :user, as: :select %>
  <%= f.input  :title %>
  <%= f.input  :summary, as: :text %>
  <%= f.input  :body, as: :text %>
  <%= f.input  :remote_featured_image_url, label: 'Featured Image', wrapper_html: { class: "featimage-remote" } %>
  &nbsp;&nbsp;or&nbsp;&nbsp;<%= f.input  :featured, as: :file, label: false, wrapper_html: { class: "featimage-upload" } %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<!--
<%#= form_for @post do |post| %>
  <div class="container">
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= post.label :user_id %>
          </div>
          <div class="col-lg-3">
              <%#= post.select :user_id, User.all.map{ |user| [user.email, user.id] }, {}, class: 'form-control' %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= post.label :title %>
          </div>
          <div class="col-lg-3">
              <%#= post.text_field :title, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= post.label :summary %>
          </div>
          <div class="col-lg-5">
              <%#= post.text_area :summary, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= post.label :body %>
          </div>
          <div class="col-lg-5">
              <%#= post.text_area :body, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= post.label :featured_image %>
          </div>
          <div class="col-lg-5">
              <%#= post.file_field :featured_image, class: "form-control" %> or
              <%#= post.text_field :remote_featured_image_url, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-3 col-lg-offset-2">
              <%#= post.submit class: "btn btn-primary" %>
          </div>
      </div>
  </div>
<%# end %> -->

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <header class="h3">
    <%= link_to post do %>
      <%= render text: sanitize(post.title) %>
    <% end %>
  </header>
  <% if post.featured_image? %>
    <div class="media-right photo">
      <%= link_to post.featured_image.versions[:standard].url do
        image_tag post.featured_image.versions[:thumbnail].url,
                  class: "img-responsive",
                  alt: post.summary
      end %>
    </div>
  <% else %>
    <div class="media-right">
      <p>
        Sorry, no photo here, bub.
      </p>
    </div>
  <% end %>
  <article>
      <%= render html: sanitize(post.body) %>
  </article>
  <br /><br />

<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |new_post| %>

  <div>
    <%= new_post.label :title %>
    <%= new_post.text_area :title %>
  </div>
  <div>
    <%= new_post.label :summary %>
    <%= new_post.text_area :summary %>
  </div>
  <div>
    <%= new_post.label :body %>
    <%= new_post.text_area :body %>
  </div>
  <div>
    <%= new_post.label :user_id %>
    <%= new_post.select :user_id, User.all.map{ |user| [user.email, user.id] } %>
  </div>
  <div>
    <%= new_post.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/show.html.erb
<header class="h3">
    <%= simple_format render text: sanitize(@post.title) %>
    <small>by <%= link_to @post.user.name, @post.user %></small>
</header>
<article>
    <% if !@post[:featured_image].blank? %>
    <div class="media-right photo">
        <% if @post.featured_image.stored_version.blank? %>
          <%= link_to @post.featured_image.url do
                image_tag @post.featured_image.url, class: "img-responsive", alt: @post.summary
              end %>
        <% else %>
          <%= link_to @post.featured_image.versions[:standard].url do
                image_tag @post.featured_image.versions[:thumbnail].url, class: "img-responsive", alt: @post.summary
              end %>
        <% end %>
    </div>
    <% end %>

    <%= render html: sanitize(@post.body) %>
</article>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="bg-danger col-lg-12">
    <ul class="list-unstyled">
      <% @user.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @user do |f| %>
  <%= f.input  :email %>
  <%= f.input  :name %>
  <%= f.input  :avatar %>
  <%= f.input  :banner %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<!-- <%#= form_for @user do |user| %>
  <div class="container">
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :name %>
          </div>
          <div class="col-lg-3">
              <%#= user.text_field :name, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :email %>
          </div>
          <div class="col-lg-5">
              <%#= user.text_field :email, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :avatar %>
          </div>
          <div class="col-lg-5">
              <%#= user.url_field :avatar, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :banner %>
          </div>
          <div class="col-lg-5">
              <%#= user.url_field :banner, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-3 col-lg-offset-2">
              <%#= user.submit class: "btn btn-primary" %>
          </div>
      </div>
  </div>
<%# end %> -->

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="bg-danger col-lg-12">
    <ul class="list-unstyled">
      <% @user.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= simple_form_for @user do |f| %>
      <%= f.input  :email, required: true %>
      <%= f.input  :password, required: true %>
      <%= f.input  :name, required: true %>
      <%= f.input  :avatar %>
      <%= f.input  :banner %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<!-- <%#= form_for @user do |user| %>
  <div class="container">
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :email %>
          </div>
          <div class="col-lg-5">
              <%#= user.text_field :email, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :password %>
          </div>
          <div class="col-lg-5">
              <%#= user.password_field :password, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :name %>
          </div>
          <div class="col-lg-3">
              <%#= user.text_field :name, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :avatar %>
          </div>
          <div class="col-lg-5">
              <%#= user.url_field :avatar, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
              <%#= user.label :banner %>
          </div>
          <div class="col-lg-5">
              <%#= user.url_field :banner, class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-3 col-lg-offset-2">
              <%#= user.submit class: "btn btn-primary" %>
          </div>
      </div>
  </div>
<%# end %> -->

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-9 col-lg-offset-3">
    <h1><%= @user.name %></h1>
    <%= image_tag @user.avatar, class: 'image-responsive pull-right' %>
  </div>
</div>

<% @user.posts.each do |post| %>

  <header class="h3">
    <%= link_to post do %>
      <%= render text: sanitize(post.title) %>
    <% end %>
  </header>
  <% if post.featured_image? %>
    <div class="media-right photo">
      <%= link_to post.featured_image.versions[:standard].url do
        image_tag post.featured_image.versions[:thumbnail].url,
                  class: "img-responsive",
                  alt: post.summary
      end %>
    </div>
  <% else %>
    <div class="media-right">
      <p>
        Sorry, no photo here, bub.
      </p>
    </div>
  <% end %>
  <article>
      <%= render html: sanitize(post.body) %>
  </article>
  <br /><br />

<% end %>